import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "SphereVista360 terms of service — rules and guidelines for using our platform.",
};

export default function TermsPage() {
  return (
    <div className="container-main py-12">
      <div className="max-w-3xl mx-auto prose prose-gray">
        <h1>Terms of Service</h1>
        <p className="lead">
          Last updated: March 13, 2026
        </p>

        <h2>Acceptance of Terms</h2>
        <p>
          By accessing and using SphereVista360, you agree to be bound by these
          Terms of Service.
        </p>

        <h2>Financial Disclaimer</h2>
        <p>
          All content on SphereVista360 is for informational and educational
          purposes only. Nothing on this site constitutes financial advice,
          investment advice, or a recommendation to buy or sell any financial
          instrument. Always consult a qualified financial advisor before making
          investment decisions.
        </p>

        <h2>AI-Generated Content</h2>
        <p>
          Some content on SphereVista360 is generated by artificial intelligence.
          While we strive for accuracy, AI-generated predictions and analysis may
          contain errors. Users should verify information independently.
        </p>

        <h2>Data Accuracy</h2>
        <p>
          Financial data is sourced from third-party providers and is provided
          &quot;as is&quot; without warranty. We do not guarantee the accuracy,
          completeness, or timeliness of any data displayed.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          SphereVista360 shall not be liable for any losses or damages arising
          from the use of information provided on this platform.
        </p>

        <h2>Contact</h2>
        <p>
          For questions about these terms, contact us at{" "}
          <a href="mailto:contact@spherevista360.com">contact@spherevista360.com</a>.
        </p>
      </div>
    </div>
  );
}
